15 Фоновые задачи
Lichers0/qna pull request #13
Opened 2021-03-03 13:19 UTC by Lichers0

Реализовать следующие истории, используя фоновые задачи:

Отправка ежедневного письма-дайджеста всем пользователям. Дайджест содержит список всех вопросов, созданных за последние сутки
Автор вопроса получает уведомление на email при появлении нового ответа на свой вопрос
Любой залогиненный пользователь может подписаться на обновления вопроса. При этом он будет получать уведомления по email при появлении новых ответов на этот вопрос. Кол-во вопросов, на которые может быть подписан пользователь не ограничено.
Пользователь может отписаться от получения уведомлений об обновлении вопроса, если он на них подписан. Отписаться можно только от вопроса, на обновления которого пользователь подписан.
Автор вопроса также может отписаться от получения уведомлений о новых ответах на его вопрос

2021-03-04 10:22 UTC, vkurennov requested changes

2021-03-04 10:22 UTC, vkurennov commented on app/controllers/subscriptions_controller.rb
> +  delegate :destroy, to: :subscription
не лучший подход для контроллера, все же он делает несколько больше, чем просто вызов метода (а именно - еще и рендеринг, пусть и неявно), поэтомму лучше в явном виде прописать экшн контрллера. Такой код в реальном проекте я бы не пропустил, это использование не того инструмента не для тех задач

2021-03-04 10:22 UTC, vkurennov commented on spec/controllers/answers_controller_spec.rb
> +  describe 'Active job notice' do
AnswersController не вызывает выполнение фоновй задачи и ничего вообще о них не знает, поэтому здесь не место этим тестам.  это надо тестировать в том классе, который инициирует вызов NewAnswerNoticeJob

2021-03-05 05:39 UTC, Lichers0 commented on app/controllers/subscriptions_controller.rb
> +  delegate :destroy, to: :subscription
Исправил, но как же быть с rails rubocop?

https://www.rubydoc.info/gems/rubocop/0.41.2/RuboCop/Cop/Rails/Delegate

2021-03-05 09:11 UTC, vkurennov commented on app/controllers/subscriptions_controller.rb
> +  delegate :destroy, to: :subscription
ну рубокоп все же статический анализатор, он не всегда может давать правильные рекомендации. в целом-то верно там все описано, но это касается например, если у нас 2 модели и одна вызывает аналогичный метод другой, т.е. если у нас классы одного слоя. А здесь у нас разные слои mvc-архитектуры, поэтому тут лучше в явном виде прописывать. Но рубокоп такие тонкости не может отследить, поэтому решения окончательное за разработчиком. Чтобы рубокоп не ругался, можно в этом файле отключить конкретную проверку

2021-03-05 09:39 UTC, vkurennov approved these changes

2021-03-05 09:39 UTC, vkurennov commented on config/routes.rb
> +  get 'subscriptions/create'
используй ресурсный роутиг. и get-запросы не могут ничего изменять в нормальной REST-архитектуре, т.е. тут грубое нарушение соглашений

2021-03-05 09:39 UTC, vkurennov commented on config/routes.rb
> +    resources :subscriptions, shallow: true, only: %i[create destroy]
вот же у тебя ресурс, зачем выше еще какие-то пути через get? их надо просто удалить

2021-03-05 09:39 UTC, vkurennov commented on app/views/subscriptions/_subscription.html.slim
> +      = button_to 'SUBSCRIBE', question_subscriptions_path(question), remote: true, data: { type: :js }
тут должен быть post-запрос

2021-03-05 11:03 UTC, Lichers0 commented on app/views/subscriptions/_subscription.html.slim
> +      = button_to 'SUBSCRIBE', question_subscriptions_path(question), remote: true, data: { type: :js }
button_to по умолчанию же post?

2021-03-05 11:05 UTC, Lichers0 commented on config/routes.rb
> +  get 'subscriptions/create'
забыл убрать...

2021-03-06 09:23 UTC, merged