Задание к уроку "Интеграционное тестирование"
Lichers0/qna pull request #3
Opened 2020-12-17 15:36 UTC by Lichers0

1. Реализовать следующие истории, начиная с acceptance-тестов (если они уже реализованы, покрыть acceptance-тестами):
  - Пользователь может создавать вопрос
  - Пользователь может просматривать список вопросов
  - Пользователь, находясь на странице вопроса, может написать ответ на вопрос (т.е. форма нового ответа должна быть прямо на странице вопроса, без перехода на другую страницу)
  - Пользователь может просматривать вопрос и ответы к нему.

 2. Добавить аутентификацию к проекту, покрыть acceptance-тестами следующие сценарии:
  - Пользователь может войти в систему
  - Пользователь может выйти из системы
  - Пользователь может зарегистрироваться в системе

 3. Реализовать следующие истоиии:
  - Только аутентифицированный пользователь может создавать вопросы и ответы
  - Автор может удалить свой вопрос или ответ, но не может удалить чужой вопрос/ответ
 

Примечание: 

- Во всех формах ставьте опцию local: true, чтобы избежать возможных проблем с отображением ошибок при реальной работе в браузере. Подробнее об этом будет рассказано в следующем уроке.

Рекомендации:

 - Можно записать основные сценарии, без реализации, а затем писать их один за другим. Для этого просто напишите  
scenario "some description"
 такие сценарии будут отображаться как pending, то есть ждущие реализации. Это для того, чтобы вы не забыли их реализовать.
 - Написали сценарий, перешли на уровень unit-тестов. Здесь двигаемся мелкими шагами "тест-код-рефакторинг, тест-код-рефакторинг". Некоторые вещи можно будет описать сразу, например, валидации и ассоциации, а какие-то будут сложнее, здесь лучше двигаться постепенно.
 - Далее описываем следующий сценарий и опять на уровень unit-тестов и так далее, пока не реализуем все сценарии
 - После того, как все сценарии проходят, подумайте, может быть есть еще какие-то сценарии, которые вы не описали. Если так, то добавьте их.
 - Для аутентификации лучше всего использовать Devise, т.к. впоследствии он нам еще пригодится

2020-12-18 06:45 UTC, IvanShamatov requested changes
Никто ведь не станет мерджить PR с сломанными на CI спеками, да?

2020-12-18 06:45 UTC, IvanShamatov commented on app/controllers/answers_controller.rb
>        render :new
На какой странице мы в таком случае окажемся? мне казалось что должны быть на странице вопроса

2020-12-18 06:45 UTC, IvanShamatov commented on app/controllers/answers_controller.rb
> +  def owner?
давай перенесем этот метод в модель юзера 
сравнивать надо айдишники, чтобы у ресурса (в данном случае answer'a) не было необходимости доставать из базы ассоциированную модель юзера

2020-12-18 06:45 UTC, IvanShamatov commented on app/controllers/questions_controller.rb
> +  def owner?
Не смущает, что у тебя уже в двух местах один и тот же метод?

2020-12-18 06:45 UTC, IvanShamatov commented on app/views/layouts/application.html.slim
> +      = notice
а что если ни notice, ни alert нет? у нас просто так в верстке валяются два блока, которые доставляют адскую боль верстальщику?)

2020-12-18 06:45 UTC, IvanShamatov commented on app/views/layouts/application.html.slim
> +      = notice
тут нужен if

2020-12-18 06:45 UTC, IvanShamatov commented on spec/controllers/answers_controller_spec.rb
> +    subject(:destroy_request) { delete :destroy, { params: { question_id: question, id: answer } } }
интересно, а зачем ты используешь именованный subject, просто для семантики? я без претензии тут, просто раньше не встречал такое

2020-12-18 09:22 UTC, Lichers0 commented on spec/controllers/answers_controller_spec.rb
> +    subject(:destroy_request) { delete :destroy, { params: { question_id: question, id: answer } } }
Rubocop ругается
https://www.rubydoc.info/gems/rubocop-rspec/1.6.0/RuboCop/Cop/RSpec/NamedSubject

2020-12-18 09:25 UTC, Lichers0 commented on app/controllers/answers_controller.rb
>        render :new
В Конечном итоге мы окажемся в контроллере AnswerController#New
Отрисуем вопрос, список ответов, а так же окно для добавления нового ответа....

2020-12-19 08:42 UTC, IvanShamatov commented on app/controllers/answers_controller.rb
>        render :new
Согласно заданию все должно происходить на странице вопроса, пожалуйста исправь

2020-12-19 08:54 UTC, IvanShamatov requested changes
Решение не соответствует заданию и есть грубые ошибки, надо переделывать

2020-12-19 08:54 UTC, IvanShamatov commented on app/controllers/questions_controller.rb
> +    redirect_to new_question_answer_path(question)
На странице show мы отрисовываем вопрос, и ответы на него, все те ответы, которые к этому вопросу дали. А еще в добавок отрисовываем форму для того чтобы этот ответ дать.

2020-12-19 08:54 UTC, IvanShamatov commented on app/controllers/questions_controller.rb
> +    question
Для простоты я рекомпндовал бы написать @question = Question.new
Тот случай, когда мы создаем if там где он не нужен. А следовательно повышаем complexity кода.

2020-12-19 08:54 UTC, IvanShamatov commented on app/controllers/questions_controller.rb
> +    if question.owner?(current_user)
Смотри, такой метод не сильно отличается от того, что было до этого. Ты этот метод добавил и в вопрлс и в ответ, а потом будет нужно добавить еще и в комменты, и в голосовалку, и в еще что-то. Не проще ли сделать то, что я рекомендовал, взять и у юзера создать метод проверки на авторство?

2020-12-19 08:54 UTC, IvanShamatov commented on app/models/concerns/owner_staff.rb
> +    user.id == check_user.id
Этот метод неправильно работает, ты берешь id пользователя и сравниваешь с id вопроса или ответа.

2020-12-19 08:54 UTC, IvanShamatov commented on spec/controllers/answers_controller_spec.rb
> +    subject(:destroy_request) { delete :destroy, { params: { question_id: question, id: answer } } }
Окей

2020-12-20 07:30 UTC, Lichers0 commented on app/models/concerns/owner_staff.rb
> +    user.id == check_user.id
Нет. Я беру id владельца вопроса или ответа и сравниваю с id пользователя, переданного параметром.

2020-12-20 07:34 UTC, Lichers0 commented on app/models/concerns/owner_staff.rb
> +    user.id == check_user.id
В моей реализации он инклудился в вопрос и ответ и в обоих моделях "есть ссылка" на владельца (user'a)

2020-12-20 16:06 UTC, IvanShamatov requested changes

2020-12-21 06:27 UTC, IvanShamatov approved these changes

2020-12-21 06:27 UTC, IvanShamatov commented on .github/workflows/ruby.yml
> +      - name: Webpack compile
лишний шаг, webpacker:install генерирует код, этот код у тебя уже должен быть в кодовой базе к моменту запуска workflow

2020-12-21 06:27 UTC, IvanShamatov commented on app/models/concerns/owner_staff.rb
> +  def owner?(model)
этот модуль используется в одном единственном месте. Логично было бы его в модели и оставить

2020-12-21 06:27 UTC, IvanShamatov commented on app/views/questions/_question.html.slim
> +  p= question.body
вот этот знак "стоп" в конце строки означает, что файл сохранен без переноса строки в конце.
https://stackoverflow.com/questions/729692/why-should-text-files-end-with-a-newline вот тут о том, почему это важно. В любом редакторе можно настроить правильное закрытие последней строки при сохранение файла

2020-12-21 06:27 UTC, IvanShamatov commented on app/views/questions/show.html.slim
> += link_to 'Delete question', question_path(@question), method: :delete if @question.user == current_user
вот здесь тоже owner? метод подошел бы. Чем дальше, тем больше у тебя будет мест, где во вьюшке что-то будет в зависимости от авторства отрисовываться

2020-12-21 06:27 UTC, IvanShamatov commented on db/migrate/20201216063705_add_user_to_question.rb
> +    add_reference :questions, :user, null: false, foreign_key: true, default: 1
откуда этот default: 1 взялся? Это генератором выставленное значение? Что-то есть большие вопросы к тому, что это должно быть 1...
Скорее всего это ты написал миграцию, а потому что она не проходила, ты решил вписать туда первого пользователя. Если что ключи могут совсем не с 1 начинаться. Это не то чтобы нехорошая практика, это поведение, которое ведет к ошибке. С чего вдруг мы можем знать, что в продакшене именно 1й пользователь автор всех вопросов и ответов? и что вообще он существует именно с таким id.
В общем эти миграции должны накатываться на пустой базе, когда ни вопросов, ни ответов еще нет, а default выставлять нельзя

2020-12-21 06:55 UTC, Lichers0 commented on db/migrate/20201216063705_add_user_to_question.rb
> +    add_reference :questions, :user, null: false, foreign_key: true, default: 1
Взялся он от rubocopa

2020-12-21 06:56 UTC, Lichers0 commented on db/migrate/20201216063705_add_user_to_question.rb
> +    add_reference :questions, :user, null: false, foreign_key: true, default: 1
db/migrate/20201217055233_add_user_to_answer.rb:5:36: C: Rails/NotNullColumn: Do not add a NOT NULL column without a default value.

2020-12-21 06:59 UTC, Lichers0 commented on db/migrate/20201216063705_add_user_to_question.rb
> +    add_reference :questions, :user, null: false, foreign_key: true, default: 1
Ну и как тут поступать? Исключу для папки, будет пропускать не reference поля....

2020-12-21 10:54 UTC, merged